import React from 'react';

const Dashboard: React.FC = () => {
    return (
        <div className="page dashboard-page">
            <div className="page-heading"><div><p className="eyebrow">Tuesday, March 12, 2024</p><h1>Good morning, Alex<span className="accent">.</span></h1><p className="lede">Here is a clear view of your academic progress and what is coming next.</p></div><button className="primary-button">View full report <span>-&gt;</span></button></div>
            <section className="hero-panel"><div><p className="eyebrow light">Current standing</p><h2>On track for<br /><em>distinction.</em></h2><p className="hero-copy">Your performance is trending above your semester target. Keep the momentum through finals.</p></div><div className="progress-ring"><strong>86</strong><span>/ 100</span><small>overall score</small></div><div className="hero-meta"><div><strong>3.72</strong><span>Current GPA</span></div><div><strong>14 / 18</strong><span>Credits complete</span></div></div></section>
            <div className="section-heading"><h2>At a glance</h2><span>Spring semester 2024</span></div>
            <section className="stats-grid"><div className="stat-card"><span className="stat-label">Attendance</span><strong>94.8%</strong><div className="mini-bar"><i style={{ width: '94.8%' }} /></div><span className="stat-note positive">+2.4% from last month</span></div><div className="stat-card"><span className="stat-label">Assignments</span><strong>18 <small>/ 22</small></strong><div className="mini-bar"><i style={{ width: '81%' }} /></div><span className="stat-note">4 due this week</span></div><div className="stat-card"><span className="stat-label">Study hours</span><strong>24.5 <small>hrs</small></strong><div className="mini-bar orange"><i style={{ width: '68%' }} /></div><span className="stat-note">Goal: 30 hrs / week</span></div></section>
            <section className="lower-grid"><div className="surface upcoming"><div className="section-heading"><h2>Coming up</h2><a href="/schedule">View schedule -&gt;</a></div><div className="event-row"><div className="date-block"><b>13</b><span>MAR</span></div><div><strong>UX Research Methods</strong><p>Room B-204 <span>09:00 - 10:30</span></p></div><span className="event-type">LECTURE</span></div><div className="event-row"><div className="date-block"><b>14</b><span>MAR</span></div><div><strong>Database Systems</strong><p>Lab C-12 <span>13:00 - 15:00</span></p></div><span className="event-type teal">LAB</span></div><div className="event-row"><div className="date-block"><b>15</b><span>MAR</span></div><div><strong>Design portfolio review</strong><p>Online session <span>11:00 - 12:00</span></p></div><span className="event-type purple">REVIEW</span></div></div><div className="surface activity"><div className="section-heading"><h2>Recent activity</h2><span>Last 7 days</span></div><div className="activity-item"><span className="activity-icon teal-bg">A</span><div><strong>Assignment submitted</strong><p>Interaction Design - Project 02</p></div><time>2h ago</time></div><div className="activity-item"><span className="activity-icon orange-bg">B</span><div><strong>New grade posted</strong><p>Database Systems - Quiz 04</p></div><time>Yesterday</time></div><div className="activity-item"><span className="activity-icon navy-bg">N</span><div><strong>Course announcement</strong><p>UX Research Methods</p></div><time>Mar 08</time></div></div></section>
        </div>
    );
};

export default Dashboard;